apiVersion: v2
name: kps
description: Install kube-prometheus stack to generate and expose cluster-level metrics
type: application
version: 50.3.1
appVersion: v0.67.1
dependencies:
  - name: prometheus-operator-crds
    version: "5.1.0"
    repository: https://prometheus-community.github.io/helm-charts
    # condition: kubeStateMetrics.enabled
  - name: kube-state-metrics
    version: "5.12.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.23.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.59.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: prometheus-windows-exporter
    repository: https://prometheus-community.github.io/helm-charts
    version: "0.1.*"
    condition: windowsMonitoring.enabled
