apiVersion: v2
# name: kps
description: Install kube-prometheus stack to generate and expose cluster-level metrics
type: application
version: 50.3.1
appVersion: v0.67.1
name: kube-prometheus-stack
# sources:
#   - https://github.com/prometheus-community/helm-charts
#   - https://github.com/prometheus-operator/kube-prometheus
# home: https://github.com/prometheus-operator/kube-prometheus
# keywords:
#   - operator
#   - prometheus
#   - kube-prometheus
# annotations:
#   "artifacthub.io/license": Apache-2.0
#   "artifacthub.io/operator": "true"
#   "artifacthub.io/links": |
#     - name: Chart Source
#       url: https://github.com/prometheus-community/helm-charts
#     - name: Upstream Project
#       url: https://github.com/prometheus-operator/kube-prometheus

dependencies:
  # - name: prometheus
  #   version: "24.3.0"
  #   repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-operator-crds
    version: "5.1.0"
    repository: https://prometheus-community.github.io/helm-charts
    # condition: kubeStateMetrics.enabled
  - name: kube-state-metrics
    version: "5.12.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.23.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.59.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: prometheus-windows-exporter
    repository: https://prometheus-community.github.io/helm-charts
    version: "0.1.*"
    condition: windowsMonitoring.enabled
  # - name: alertmanager
  #   repository: https://prometheus-community.github.io/helm-charts
  #   version: "1.6.0"
