apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ksm
  labels:
    app: monitoring
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/kube-prometheus-stack
    repoURL: 'https://github.com/jtvertigo/argocd-monitoring'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
